version: 2
jobs:
    build:
      branches:
        only:
          - develop
      docker:
        - image: srcml/ubuntu_x86_64_base
      steps:
        - checkout
        - run: apt-get update
        - run: apt-get install -y git ssh xsltproc
        - run: git submodule update --init --recursive
        - run: mkdir build
        - run: cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
        - run: cd build && make && make install && ldconfig
        - run: ln -s build/bin bin
        - run: cd test/parser && srcml --parser-test testsuite
