package edu.udel.nlpa.swum.utils.constants;

public enum RuleIndicator {
	VERB_PHRASE, NOUN_PHRASE, CONSTRUCTOR, PREPOSITIONAL_PHRASE, UNKOWN,
	BASE_VERB, V_3PS, V_3P_IRR, V_MODAL, VERB_VERB, ED_VERB, ING_VERB,  
	PREP, BASE_VERB_PREP, AJ, AV, DT, SPECIAL, DIGIT, EVENT_PARAM, 
	ENDS_WITH_ED, ENDS_WITH_ING, VOID_NP, FIELD, EMPTY
}
